# This is a config for E2B sandbox template.
# You can use template ID (jg0cxpc1975wcafr0fvr) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("jg0cxpc1975wcafr0fvr") # Sync sandbox
# sandbox = await AsyncSandbox.create("jg0cxpc1975wcafr0fvr") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('jg0cxpc1975wcafr0fvr')

team_id = "fa04bbd2-33ad-4e8e-badb-4caa88913ece"
start_cmd = "/compile_frontend.sh"
dockerfile = "e2b.Dockerfile"
template_id = "jg0cxpc1975wcafr0fvr"
